# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20160226_2044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='buser',
            table='buser',
        ),
        migrations.AlterModelTable(
            name='fuser',
            table='fuser',
        ),
    ]
