# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20160229_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_serial',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
